version: '3'
services:
  black_follow:
    image: black_follow
    build:
      context: .
      dockerfile: black_follow/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - blackfollow-network

  postgres:
    image: postgres:latest
    container_name: blackfollow.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10109989
      POSTGRES_DB: blackfollow2
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    networks:
      - blackfollow-network

  nginx:
    image: nginx:latest
    container_name: blackfollow.nginx
    ports:
      - "80:80"  # Expose port 80 for public access
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the nginx.conf file
    depends_on:
      - black_follow
    networks:
      - blackfollow-network

networks:
  blackfollow-network:
    driver: bridge
