name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the latest code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify Docker Compose installation

      # 3. Log in to Docker Hub using Docker Access Token
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # Docker Access Token (instead of password)

      # 4. Build and push Docker image using Docker Compose
      - name: Build and Push Docker Image using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Set up SSH agent with the private key stored in GitHub secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 2. Deploy to the server via SSH, pull the Docker image from Docker Hub and restart the containers
      - name: Pull Docker Image and Restart Containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Navigate to the project directory
            cd /path/to/your/project  # Replace with your project path on the server
            
            # Pull the latest Docker image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/black_follow:latest

            # Rebuild and restart Docker containers
            docker-compose down
            docker-compose up -d --build
          EOF

      # 3. Send Telegram success message
      - name: Send Telegram Success Message
        if: success()
        run: |
          curl -s --data "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
                   --data "text=Deployment Successful: The application has been successfully updated on the server!" \
                   "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"

      # 4. Send Telegram failure message
      - name: Send Telegram Failure Message
        if: failure()
        run: |
          curl -s --data "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
                   --data "text=Deployment Failed: There was an error during deployment." \
                   "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
